# Generated by Django 3.2 on 2023-08-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_manodeobra_tipo_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcioncotizacion',
            name='descuento_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='descripcioncotizacion',
            name='descuento_tipo',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('manual', 'Manual')], default='porcentaje', max_length=10),
        ),
    ]
